### PR TITLE
relaxing validation for repository

### PR DESCRIPTION
**Pull request by vkorehov**
this validation breaks installation from http repo!

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Hi @vkorehov 

Thanks for submitting this PR. 

Could you please squash the commits and add a bit more descriptive PR title ?

**Comment by sheenaajay** [comment]
@vkorehov Thanks for submitting the PR. Is it a WIP status?

**Comment by bFekete** [comment]
@vkorehov Check out my PR #201 . It looks like we both automated namespace_bindings, shared_libraries, and auth aliases.

**Comment by david22swan** [comment]
@vkorehov 
Just making a quick update to re-target your pr towards the newly default main branch. Apologies if this is an inconvenience in any way.

**Comment by sheenaajay** [comment]
Hi @vkorehov  - I'm just closing this PR as part of the IAC Team's audit of stale PRs. 
Thanks for the submission and ping us any time if you want to pick it up again.Also the following PR is merged https://github.com/puppetlabs/puppetlabs-websphere_application_server/pull/201 which automates namespace_bindings, shared_libraries, and auth aliases. Thanks for your contribution.

**Pull request closed without merging**
