### PR TITLE
Puppet 4 data type checking

### PR DESCRIPTION
**Pull request by logicminds**
This PR adds data types to all the parameters and adds unit testing for every manifest.

The majority of the validate_XX functions were removed as they were no longer needed as well as some conditional logic that was replaced with parameter variable interpolation. 

Example:

```
  Optional[Stdlib::AbsolutePath] $profile_base  = "${target}/profiles",
```
Vs

```
if $profile_base {
    $_profile_base = $profile_base
  } else {
    $_profile_base = "${_target}/profiles"
  }
```

This removed many intermediate variables and provides a cleaner manifest.   This type of refactor also assumes puppet 4.10 is being used as parameter dependencies are now being utilized. 

This also means any attempt of moving parameter dependencies out of the correct order will result in a error (caught by unit testing).  Do not sort the parameter list by alpha numeric order!

The next release will need to be a major release as a result of this change.

The previous code also used strings for representing numbers.  I decided to use the `Stdlib::Compat::Integer` data type here for these cases because the Integer type was too strict.  I didn't want previous module users to have to update their data to numbers in order to use the new version.  So the `Stdlib::Compat::Integer` will allow for strings and numbers ('23', 23).

I have also added the puppet-debugger as a development dependency and the puppet-debug module to aid in development.

### CODE REVIEW

**Comment by logicminds** [comment]
I have not run any acceptance tests yet as I was hoping travis would kick these off.

**Comment by sheenaajay** [comment]
Thanks for submitting the PR @logicminds .Travis doesn't run acceptance tests for this module :-(.
I have run the adhoc job for this PR.WIll update you with the results. Thanks again for this contribution.

**Comment by sheenaajay** [comment]
@logicminds Please find the Test results.Please let us know if you need more information.
`13:03:59 Failures:
13:03:59 
13:03:59   1) IHS instance runs without errors
13:03:59      Failure/Error: expect(@result.exit_code).to eq 2
13:03:59        
13:03:59        expected: 2
13:03:59             got: 1
13:03:59        
13:03:59        (compared using ==)
13:03:59        
13:03:59      # ./spec/acceptance/ihs_spec.rb:23:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   2) IHS instance shall start an ihs server process
13:03:59      Failure/Error: ports_ihs_listening = on(@agent, "lsof -ti :#{@listen_port}").stdout.split
13:03:59      Beaker::Host::CommandFailure:
13:03:59        Host 'he9fhcup5rd8wqg.delivery.puppetlabs.net' exited with 1 running:
13:03:59         lsof -ti :10080
13:03:59        Last 10 lines of output were:
13:03:59        
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/host.rb:391:in `exec'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
13:03:59      # ./spec/acceptance/ihs_spec.rb:30:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   3) IHS instance shall be listening on the correct port
13:03:59      Failure/Error: ports_ihs_listening = on(@agent, "lsof -ti :#{@listen_port}").stdout.split
13:03:59      Beaker::Host::CommandFailure:
13:03:59        Host 'he9fhcup5rd8wqg.delivery.puppetlabs.net' exited with 1 running:
13:03:59         lsof -ti :10080
13:03:59        Last 10 lines of output were:
13:03:59        
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/host.rb:391:in `exec'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
13:03:59      # ./spec/acceptance/ihs_spec.rb:43:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   4) IHS instance shall respond to http queries
13:03:59      Failure/Error: expect(response_lines[0]).to match(%r{^<title>IBM HTTP Server(.*)+</title>$})
13:03:59        expected nil to match /^<title>IBM HTTP Server(.*)+<\/title>$/
13:03:59        
13:03:59      # ./spec/acceptance/ihs_spec.rb:52:in `block (3 levels) in <top (required)>'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:93:in `block in on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
13:03:59      # ./.bundle/gems/gems/beaker-4.11.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
13:03:59      # ./spec/acceptance/ihs_spec.rb:48:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   5) IHS instance behaves like an idempotent resource runs without errors
13:03:59      Failure/Error: expect(@result.exit_code).to eq 2
13:03:59        
13:03:59        expected: 2
13:03:59             got: 1
13:03:59        
13:03:59        (compared using ==)
13:03:59        
13:03:59      Shared Example Group: "an idempotent resource" called from ./spec/acceptance/ihs_spec.rb:26
13:03:59      # ./spec/support/examples/idempotent_resource.rb:3:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   6) IHS instance behaves like an idempotent resource runs a second time without changes
13:03:59      Failure/Error: expect(second_result.exit_code).to eq 0
13:03:59        
13:03:59        expected: 0
13:03:59             got: 1
13:03:59        
13:03:59        (compared using ==)
13:03:59        
13:03:59      Shared Example Group: "an idempotent resource" called from ./spec/acceptance/ihs_spec.rb:26
13:03:59      # ./spec/support/examples/idempotent_resource.rb:9:in `block (2 levels) in <top (required)>'
13:03:59 
13:03:59   7) IHS instance shall stop the IHS server runs without errors
13:03:59      Failure/Error: expect(@result.exit_code).to eq 2
13:03:59        
13:03:59        expected: 2
13:03:59             got: 1
13:03:59        
13:03:59        (compared using ==)
13:03:59        
13:03:59      # ./spec/acceptance/ihs_spec.rb:73:in `block (3 levels) in <top (required)>'
13:03:59 
13:03:59   8) IHS instance shall stop the IHS server runs a second time without changes
13:03:59      Failure/Error: expect(second_result.exit_code).to eq 2
13:03:59        
13:03:59        expected: 2
13:03:59             got: 1
13:03:59        
13:03:59        (compared using ==)
13:03:59        
13:03:59      # ./spec/acceptance/ihs_spec.rb:85:in `block (3 levels) in <top (required)>'
13:03:59 
13:03:59 Finished in 28 minutes 25 seconds (files took 15 minutes 51 seconds to load)
13:03:59 52 examples, 8 failures`

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in about six months, I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules`  with an @ sign in front and we'll re-open this pull request.

Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Comment by logicminds** [comment]
I completely forgot about this.  I would still like to rebase and fix things to get this work merged.  The main problem is the testing strategy is locked into only allowing puppet employees to run acceptance tests.  This creates a huge lag in the feedback look that blocks me.

**Pull request closed without merging**
