### PR TITLE
A Puppet Plan which can be used to clone an IBM WAS Package/FixPack repository

### PR DESCRIPTION
**Pull request by psreed**
Likely needs some testing. I wrote this plan last week and modified it heavily to include here in the official WAS plugin. See documentation in line within the plan itself.

### CODE REVIEW

**Comment by lionce** [comment]
Hello @psreed ,

Thank you for this contribution. In order to merge it, please add some tests to cover these changes. 

Cheers!

**Comment by psreed** [comment]
@lionce I'd love to.... just not quite sure how. I'll gladly do it, but any change you point me at an example for how tests for Bolt plans are normally done?

**Comment by carabasdaniel** [comment]
Hi @psreed 

Thanks for submitting this PR. In order to run tests for Bolt plans or Bolt tasks you can use the documentation from https://github.com/puppetlabs/bolt/blob/master/developer-docs/bolt_spec-run.md. 

See the example guide for writing tasks here: https://puppet.com/blog/writing-robust-bolt-tasks-guide/

**Comment by sheenaajay** [comment]
Thanks @psreed  for submitting the PR. We can always accept new PR for blot plan tests. Looking for more contribution.

**Pull request merged**
